name: mrz_scanner
description: A package that allows you to Scan any kind of documents that have any mrz format
version: 0.0.1+3
homepage: https://github.com/F-BONAPARTA/mrz_scanner

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  mrz_parser: ^2.0.0
  google_mlkit_text_recognition: ^0.4.0
  camera: ^0.10.0+4
  google_mlkit_commons: ^0.2.0
  camera_platform_interface: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
